repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: [
          "--py310-plus"
        ]

  - repo: https://github.com/psf/black # local repository
    rev: 22.8.0
    hooks:
      - id: black # for instrument black lib ( in black docs for pre commit cklishe
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10